name: armas
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pandas=1.5.3
  - python=3.8.13
  - pip=23.3.1
  - pip:
    - ipywidgets==8.1.1                    
    - fastapi==0.104.1                     
    - uvicorn==0.24.0.post1                
    - python-multipart==0.0.6              
    - autogluon==0.8.2                     
    - librosa==0.10.1                     
